target:revers-string palindrom

clean: 
	rm -f revers-string palindrom

revers-string: revers-string.c
	gcc -o revers-string revers-string.c -Wall


palindrom: palindrom.c
	gcc -o palindrom palindrom.c -Wall

